### ISSUE TITLE
Strange question

### ISSUE THREAD

**Issue by zenglongjin** [zitsen/iClusterPlus#1]
Dear zitsen:
We get an error that wasn't there before when we use tune.iClusterBayes function, showing as follow:
Error in iClusterBayes(dt1, dt2, dt3, dt4, dt5, dt6, type, x, n.burnin,  :Error: nrow(dt1) != nrow(dt2) .
Thank you very much for your attention and consideration.
Sincerely yours,
Zenglongjin

**Comment by zitsen** [comment]
This is an fix version of iClusterPlus but I'm not the author of the package. I'm sorry that I can't help you with the details. You can ask the user by their email: Qianxing Mo <qianxing.mo at moffitt.org>, Ronglai Shen <shenr at mskcc.org>

**Comment by zenglongjin** [comment]
Dear Linhe Huo:
We found that we forgot the input file, but now we change it.

Thank you very much for your attention and consideration.

Sincerely yours,

Longjin Zeng





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linhe ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 上午10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zitsen/iClusterPlus] Strange question (#1)





 
Closed #1.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
